### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by divya0056** [jeimison3/MPUOrientation#1]
IC:\\Users\\***\\Documents\\Arduino\\libraries\\MPU9250-master" "C:\\Users\\***\\AppData\\Local\\Temp\\arduino_build_751793\\sketch\\ESP-Kalman-Compass.ino.cpp" -o "C:\\Users\\***\\AppData\\Local\\Temp\\arduino_build_751793\\sketch\\ESP-Kalman-Compass.ino.cpp.o"
In file included from C:\Users\***\Documents\Arduino\libraries\MPU9250-master/MPU9250.h:8:0,

                 from C:\Users\***\AppData\Local\Temp\arduino_modified_sketch_715579\ESP-Kalman-Compass.ino:16:

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:158:1: error: stray '\302' in program

 © 202

 ^

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:158:1: error: stray '\251' in program

In file included from C:\Users\***\AppData\Local\Temp\arduino_modified_sketch_715579\ESP-Kalman-Compass.ino:19:0:

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:158:1: error: stray '\302' in program

 © 202

 ^

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:158:1: error: stray '\251' in program

In file included from C:\Users\***\Documents\Arduino\libraries\MPU9250-master/MPU9250.h:8:0,

                 from C:\Users\***\AppData\Local\Temp\arduino_modified_sketch_715579\ESP-Kalman-Compass.ino:16:

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:62:5: error: 'i2c_queue_t' does not name a type

     i2c_queue_t * i2cQ;

     ^

C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master/Wire.h:158:4: error: expected unqualified-id before numeric constant

 © 202

    ^

Using library MPUOrientation-master at version 1.0.0 in folder: C:\Users\***\Documents\Arduino\libraries\MPUOrientation-master 
Using library MPU9250-master at version 0.1.1 in folder: C:\Users\***\Documents\Arduino\libraries\MPU9250-master 
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by jeimison3** [comment]
Are you using the MPU9250 library from my GitHub? In [this repository](https://github.com/jeimison3/MPU9250).
And using the core from stickbreaker? [This repository](https://github.com/stickbreaker/arduino-esp32/tree/patch-2).
If you want, can use just the code from Readme. However you need first to solve I2C problems (Wire.h) at the native library of ESP32.

**Comment by divya0056** [comment]
Ok, Thanks got it.
